version: "3.7"
services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3001:3000
    volumes:
    - ./grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - 8086:8086
#    environment:
#      - INFLUXDB_DB=telegraf
#      - INFLUXDB_USER=telegraf
#      - INFLUXDB_ADMIN_ENABLED=true
#      - INFLUXDB_ADMIN_USER=admin
#      - INFLUXDB_ADMIN_PASSWORD=Welcome1
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    ports:
    - "8125:8125/udp"
#    extra_hosts:
#      - "influxdb:192.168.0.110"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro