

server.port: 8080

# see https://stackoverflow.com/questions/44474160/spring-integration-display-warning-that-header-is-ignored-for-population-because
#logging.level.org.springframework.integration.support.MessageBuilder: WARN
#logging.level.org.springframework.boot: INFO

management.metrics.export:
  influx.enabled: false
  jmx.enabled: false
  prometheus.enabled: false
  newrelic.enabled: false
  signalfx.enabled: false

management.endpoints.web.exposure.include: '*'
management.metrics.export.statsd:
  enabled: true
  flavor: telegraf
  host: localhost
server:
  tomcat:
    mbeanregistry:
      enabled: true
management:
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests:
              - 0.5
              - 0.95
              - 0.99
              - 1
